import {RF} from '@theme';
import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  mt5: {marginLeft: RF(5)},
  v: {marginTop: RF(20)},
  txt: {marginTop: RF(-120), marginBottom: RF(10)},
  cre: {
    width: '100%',
    height: RF(255),
    resizeMode: 'contain',
  },
  img_bg: {
    width: '100%',
    height: RF(455),
    alignItems: 'center',
    justifyContent: 'center',
  },
  mt: {marginTop: RF(25)},
  imgBG: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -70,
  },
  scrollview: {flex: 1, marginTop: RF(10)},
  tab: {
    borderRadius: RF(40),
    flexDirection: 'row',
    height: RF(40),
    alignItems: 'center',
    justifyContent: 'space-around',
    marginHorizontal: RF(10),
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 0.5},
    shadowOpacity: 0.5,
    shadowRadius: 1,
    width: '80%',
    elevation: 1,
    alignSelf: 'center',
  },
  box: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    marginTop: RF(25),
    marginBottom: RF(30),
  },
  arr: {
    width: RF(10),
    height: RF(10),
    resizeMode: 'contain',
    marginRight: RF(17),
  },
  imgV: {
    borderWidth: 1,
    width: RF(146),
    height: RF(37),
    borderColor: '#999D9E40',
    borderRadius: RF(20),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  copyTxt: {
    width: RF(80),
    height: RF(30),
    alignItems: 'center',
    borderRadius: RF(20),
    justifyContent: 'center',
    marginRight: RF(5),
  },
  copy: {
    backgroundColor: '#D2D2D21A',
    width: '100%',
    height: RF(40),
    borderRadius: RF(20),
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: RF(20),
  },
  chart: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: RF(20),
  },
  mv: {marginVertical: RF(10)},
  w: {width: '102%'},
  paymentView: {
    width: '90%',
    height: RF(160),
    backgroundColor: '#19383A',
    borderRadius: RF(20),
    alignSelf: 'center',
    marginTop: RF(30),
    paddingHorizontal: RF(20),
  },
  lastView: {
    marginBottom: RF(100),
  },
  img: {
    width: '100%',
    height: RF(278),
    resizeMode: 'contain',
    marginTop: RF(20),
  },
  content: {
    // marginTop: RF(100),
  },
  bottom_view: {
    width: '90%',
    height: RF(42),
    backgroundColor: '#19383A',
    borderRadius: RF(30),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: RF(20),
  },
  bottom_view_points: {
    width: '90%',
    height: RF(42),
    backgroundColor: '#fff',
    borderRadius: RF(30),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#4A55681A',
    flexDirection: 'row',
    marginLeft: RF(7),
    marginTop: RF(20),
  },
  image: {width: RF(24), height: RF(24), resizeMode: 'contain'},
  p: {
    // flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
});
